### ISSUE TITLE
Documentation mismaches

### ISSUE THREAD

**Issue by carleshf** [mutalyzer/backtranslate#11]
**Describe the bug**
Documentation on [PyPI](https://pypi.org/project/backtranslate/) and on [ReadTheDocs](https://mutalyzer-backtranslate.readthedocs.io/en/latest/index.html) shows different functionally and different usage of the package.

**Additional context**
I end up here from [mutalyzer](https://mutalyzer.nl/back-translato) looking for a systematic way to back-translate proteins to cDNA. As suggested by the text:

> The underlying algorithm is also available as a command line utility and programming library (source, package).

**Comment by jfjlaros** [comment]
~~It seems that the link on the Mutalyzer 2 website is outdated, it should point to the [current](https://pypi.org/project/mutalyzer-backtranslate/) package.~~

@mihailefter Could you check which version Mutalyzer 2 depends on and whether this link is indeed outdated?

**Comment by carleshf** [comment]
Thanks for the new!

Just a question, is there, then any function to translate from protein format to cDNA format in `mutalyzer-backtranslate` as it does _Back Translator_ in mutalyzer?

**Comment by jfjlaros** [comment]
This is a pure programming library, it has no HGVS support in itself.

It should be relatively straightforward to generate `g.` or `n.` descriptions from the output, then the [API](https://mutalyzer.nl/webservices) could be used to convert these descriptions.

**Comment by jfjlaros** [comment]
Just for the record, Mutalyzer 2 uses the old version of the `backtranslate` package, so the link on the website is correct.
