### ISSUE TITLE
Backtranslate does not work for NP_004324.2:p.Val600Lys

### ISSUE THREAD

**Issue by dsonkin** [mutalyzer/backtranslate#12]
Hello

Backtranslate does not work for NP_004324.2:p.Val600Lys, probably because it requires change in 2 nucleotides (NM_004333.6:c.1798_1799delinsAA). 

Thank you
Dmitriy

**Comment by jfjlaros** [comment]
Indeed, the back translator only works for single nucleotide substitutions.

From the [documentation](https://mutalyzer-backtranslate.readthedocs.io/en/latest/introduction.html): "[...] we restrict ourselves to substitutions of one nucleotide that may explain the observed amino acid change."
